---

fs_version: "v1.6.5"
public_ip: "x.x.x.x"
mongo_ip: "x.x.x.x"
postgres_ip: "x.x.x.x"
fs_curl_ip: "x.x.x.x"
fs_curl_port: "9894"
postgres_db: "telecmi"
postgres_username: "telecmi"
postgres_password: "x.x.x.x"
postgres_core_db: "freeswitch"
postgres_core_username: "freeswitch"
postgres_core_password: "freeswitch"
mongo_db: "telecmi"
freeswitch_owner: "freeswitch"
freeswitch_group: "daemon"
plivo_username: "telecmi"
plivo_password: "x.x.x.x"
